In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
c[0]

1

In [21]:
c[0]=100

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
d = np.copy(a)

In [25]:
d

array([100,   2,   3,   4])

In [26]:
a[1] = 400

In [27]:
a

array([100, 400,   3,   4])

In [28]:
d

array([100,   2,   3,   4])

In [29]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [34]:
np.fromstring('4,5', sep = ',')

array([4., 5.])

#### Python Numpy - Data Types

In [35]:
l = [2,3,4,5,6]

In [36]:
ar = np.array(l)
ar

array([2, 3, 4, 5, 6])

In [37]:
ar.ndim

1

In [38]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [39]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [41]:
ar2.ndim

2

In [42]:
ar.size

5

In [43]:
ar2.size

8

In [44]:
ar.shape

(5,)

In [45]:
ar2.shape

(2, 4)

In [46]:
ar.dtype

dtype('int32')

In [47]:
ar2.dtype

dtype('int32')

In [48]:
ar22 = np.array([(1.4,45,45),(23,45,66)])
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [49]:
ar22.dtype

dtype('float64')

In [51]:
list(range(5))

[0, 1, 2, 3, 4]

In [52]:
list(range(1,5))

[1, 2, 3, 4]

In [53]:
### But
list(range(1.5, 5))

TypeError: 'float' object cannot be interpreted as an integer

In [54]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [55]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [56]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [58]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [64]:
np.ones(4)

array([1., 1., 1., 1.])

In [65]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
on = np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [69]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [70]:
on * 4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [71]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [75]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [76]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [83]:
arr = np.random.randn(3,4)
arr

array([[ 0.61682324, -0.51145371,  0.05949714,  0.52996865],
       [-2.05128762,  0.63342473, -0.29523821, -1.02942314],
       [ 1.49420154,  0.02780677,  2.4216901 ,  1.13653283]])

In [84]:
import pandas as pd

In [85]:
pd.DataFrame(arr)

0         1         2         3
0  0.616823 -0.511454  0.059497  0.529969
1 -2.051288  0.633425 -0.295238 -1.029423
2  1.494202  0.027807  2.421690  1.136533

In [86]:
np.random.rand(3,4)

array([[0.71407383, 0.97949847, 0.06792336, 0.55503408],
       [0.34395541, 0.05373396, 0.60211756, 0.28839133],
       [0.38726767, 0.65088205, 0.70030977, 0.7333994 ]])

In [87]:
np.random.randint(1,110, (3,4))

array([[102,  20,  48,  76],
       [ 78,  73,  16,  43],
       [ 49,  27,  19,  57]])

In [88]:
np.random.randint(1,110, (300,400))

array([[ 47,  92,  89, ...,  79,  99,  16],
       [ 70,  79,  30, ...,  82,  76,  30],
       [ 19,  34,  92, ...,  89, 105,  87],
       ...,
       [101,  36,  36, ...,  35,  31,  42],
       [ 92,  67,  67, ..., 109,  47,  96],
       [ 76,  43,  57, ...,  61,  82,  48]])

In [89]:
pd.DataFrame(np.random.randint(1,110, (300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0      2   22    4   88   97   34   92   60  108   93  ...   26   71   75   
1    104  107   22   18    7   74   80   32   41   36  ...   94   47   93   
2     13   58    5   67   77   65   30    1   60   20  ...   23   19    4   
3     63   14   79    6   53   27    6   62   38   43  ...   91   47    3   
4     60   93   54   96   97   93   28   30   32   48  ...   70   45   64   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   15  102   89   76    4   97   19   92   67   76  ...   12   37   93   
296  102   89   31    1   65   82   99   51   61   98  ...   54   79    5   
297  101   34   70   88   15  102    6   13    8   19  ...  109   28   24   
298   76   62   32   28   41    1    3  102   10   33  ...   86   90   98   
299   10   38   82   20   57  106   50   58   58   19  ...   21   97   98   

     393  394  395  396  397  398  399  
0    106   55    7   70   91   69   33  
1     32  106   23   84   23   99   47  
2     80   44   21   88   47   66   90  
3     29   12   56    7   25   20   83  
4     98   34   59   50   64   43   67  
..   ...  ...  ...  ...  ...  ...  ...  
295   75   12   91   69    7   32   25  
296   73  104   25   97   15   10   30  
297   86  109   39  108   52   15   17  
298   55   75   47   61   80   91   95  
299   35   30   91   98   66   92   85  

[300 rows x 400 columns]

In [90]:
pd.DataFrame(np.random.randint(1,110, (300,400))).to_csv('test.csv')

In [91]:
arr = np.random.rand(3,4)

In [92]:
arr

array([[0.02158491, 0.76200618, 0.17445812, 0.91496214],
       [0.31134007, 0.37345844, 0.00860558, 0.21684082],
       [0.74915576, 0.48922072, 0.8334273 , 0.43715283]])

In [93]:
arr.reshape(6,-1)

array([[0.02158491, 0.76200618],
       [0.17445812, 0.91496214],
       [0.31134007, 0.37345844],
       [0.00860558, 0.21684082],
       [0.74915576, 0.48922072],
       [0.8334273 , 0.43715283]])

In [94]:
arr.reshape(6,6)

ValueError: cannot reshape array of size 12 into shape (6,6)

In [95]:
arr1 = arr.reshape(6,-134353553435)
arr1

array([[0.02158491, 0.76200618],
       [0.17445812, 0.91496214],
       [0.31134007, 0.37345844],
       [0.00860558, 0.21684082],
       [0.74915576, 0.48922072],
       [0.8334273 , 0.43715283]])

In [96]:
arr1[1]

array([0.17445812, 0.91496214])

In [97]:
arr1[1][1]

0.9149621375353353

In [98]:
arr1[2:5]

array([[0.31134007, 0.37345844],
       [0.00860558, 0.21684082],
       [0.74915576, 0.48922072]])

In [99]:
arr1[2:5,1]

array([0.37345844, 0.21684082, 0.48922072])

In [101]:
arr = np.random.randint(1, 100, (5,5))
arr

array([[64, 47, 82, 28, 39],
       [16, 66, 84, 34, 10],
       [98, 53, 51, 83, 66],
       [42, 78, 14, 41, 31],
       [83, 53, 71, 25, 94]])

In [103]:
arr > 50

array([[ True, False,  True, False, False],
       [False,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [False,  True, False, False, False],
       [ True,  True,  True, False,  True]])

In [104]:
arr[arr>50]

array([64, 82, 66, 84, 98, 53, 51, 83, 66, 78, 83, 53, 71, 94])

In [105]:
arr

array([[64, 47, 82, 28, 39],
       [16, 66, 84, 34, 10],
       [98, 53, 51, 83, 66],
       [42, 78, 14, 41, 31],
       [83, 53, 71, 25, 94]])

In [106]:
arr[2:4, [1,2]]

array([[53, 51],
       [78, 14]])

In [107]:
arr[0][0] = 5000

In [108]:
arr

array([[5000,   47,   82,   28,   39],
       [  16,   66,   84,   34,   10],
       [  98,   53,   51,   83,   66],
       [  42,   78,   14,   41,   31],
       [  83,   53,   71,   25,   94]])

In [109]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))

In [110]:
arr1

array([[1, 1, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [111]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [2, 1, 2]])

In [112]:
arr1 + arr2

array([[2, 3, 3],
       [4, 4, 3],
       [4, 3, 3]])

In [113]:
arr1 - arr2

array([[ 0, -1,  1],
       [ 0,  0,  1],
       [ 0,  1, -1]])

In [114]:
arr1*arr2

array([[1, 2, 2],
       [4, 4, 2],
       [4, 2, 2]])

In [115]:
arr1/arr2

array([[1. , 0.5, 2. ],
       [1. , 1. , 2. ],
       [1. , 2. , 0.5]])

In [116]:
arr1 @ arr2 ## for Matrix Multiplication

array([[ 7,  6,  6],
       [10, 10,  8],
       [ 8,  9,  6]])

In [117]:
arr1 / 0

C:\Users\thevk\AppData\Local\Temp/ipykernel_17980/824215542.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [118]:
arr1 +100

array([[101, 101, 102],
       [102, 102, 102],
       [102, 102, 101]])

In [119]:
arr1**2

array([[1, 1, 4],
       [4, 4, 4],
       [4, 4, 1]], dtype=int32)

#### Python Numpy - Broadcasting

In [120]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [121]:
arr = np.zeros((4,4))

In [122]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
row = np.array([1,2,3,4])

In [126]:
print(row, row.shape, row.ndim)

[1 2 3 4] (4,) 1


In [127]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [128]:
row.T

array([1, 2, 3, 4])

In [129]:
col = np.array([[1,2,3,4]])

In [130]:
col

array([[1, 2, 3, 4]])

In [131]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [133]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [134]:
arr1 = np.random.randint(1,4,(3,4))
arr1

array([[3, 1, 1, 2],
       [2, 1, 3, 3],
       [1, 3, 2, 2]])

In [135]:
np.sqrt(arr1)

array([[1.73205081, 1.        , 1.        , 1.41421356],
       [1.41421356, 1.        , 1.73205081, 1.73205081],
       [1.        , 1.73205081, 1.41421356, 1.41421356]])

In [136]:
np.exp(arr1)

array([[20.08553692,  2.71828183,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  2.71828183, 20.08553692, 20.08553692],
       [ 2.71828183, 20.08553692,  7.3890561 ,  7.3890561 ]])

In [137]:
np.log10(arr1)

array([[0.47712125, 0.        , 0.        , 0.30103   ],
       [0.30103   , 0.        , 0.47712125, 0.47712125],
       [0.        , 0.47712125, 0.30103   , 0.30103   ]])