#### Python Array Manipulation

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,4))

In [3]:
arr

array([[9, 8, 7, 2],
       [8, 1, 3, 7],
       [9, 9, 2, 6]])

In [4]:
arr.reshape(6,2)

array([[9, 8],
       [7, 2],
       [8, 1],
       [3, 7],
       [9, 9],
       [2, 6]])

In [5]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [6]:
arr.reshape(2,-266167)

array([[9, 8, 7, 2, 8, 1],
       [3, 7, 9, 9, 2, 6]])

In [7]:
arr

array([[9, 8, 7, 2],
       [8, 1, 3, 7],
       [9, 9, 2, 6]])

In [8]:
arr.T

array([[9, 8, 9],
       [8, 1, 9],
       [7, 3, 2],
       [2, 7, 6]])

In [9]:
arr.flatten()

array([9, 8, 7, 2, 8, 1, 3, 7, 9, 9, 2, 6])

In [10]:
arr1 = np.array([1,2,3,3,4])
arr1

array([1, 2, 3, 3, 4])

In [11]:
arr1.ndim

1

In [12]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [13]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 3, 4]])

In [14]:
arr

array([[9, 8, 7, 2],
       [8, 1, 3, 7],
       [9, 9, 2, 6]])

In [15]:
np.squeeze(arr)

array([[9, 8, 7, 2],
       [8, 1, 3, 7],
       [9, 9, 2, 6]])

In [16]:
data = np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [17]:
np.squeeze(data)

array([1, 2, 3])

In [18]:
arr1

array([1, 2, 3, 3, 4])

In [19]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [20]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [21]:
arr1

array([1, 2, 3, 3, 4])

In [22]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### Python Numpy - Binary Operation

In [23]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [24]:
arr1 

array([[3, 9, 4, 9],
       [9, 9, 9, 9],
       [8, 9, 2, 4]])

In [25]:
arr2

array([[4, 8, 9, 6],
       [2, 9, 1, 8],
       [8, 7, 2, 7]])

In [26]:
arr1 + arr2

array([[ 7, 17, 13, 15],
       [11, 18, 10, 17],
       [16, 16,  4, 11]])

In [27]:
arr1*arr2

array([[12, 72, 36, 54],
       [18, 81,  9, 72],
       [64, 63,  4, 28]])

In [28]:
arr1/arr2

array([[0.75      , 1.125     , 0.44444444, 1.5       ],
       [4.5       , 1.        , 9.        , 1.125     ],
       [1.        , 1.28571429, 1.        , 0.57142857]])

In [29]:
arr1-arr2

array([[-1,  1, -5,  3],
       [ 7,  0,  8,  1],
       [ 0,  2,  0, -3]])

In [30]:
arr1%arr2

array([[3, 1, 4, 3],
       [1, 0, 0, 1],
       [0, 2, 0, 4]], dtype=int32)

In [31]:
arr1 ** arr2

array([[       81,  43046721,    262144,    531441],
       [       81, 387420489,         9,  43046721],
       [ 16777216,   4782969,         4,     16384]], dtype=int32)

In [32]:
arr1 & arr2

array([[0, 8, 0, 0],
       [0, 9, 1, 8],
       [8, 1, 2, 4]], dtype=int32)

In [33]:
~arr1

array([[ -4, -10,  -5, -10],
       [-10, -10, -10, -10],
       [ -9, -10,  -3,  -5]], dtype=int32)

In [34]:
arr1|arr2

array([[ 7,  9, 13, 15],
       [11,  9,  9,  9],
       [ 8, 15,  2,  7]], dtype=int32)

In [35]:
arr1>arr2

array([[False,  True, False,  True],
       [ True, False,  True,  True],
       [False,  True, False, False]])

#### Python Numpy - String Functon

In [36]:
arr = np.array(['sudh',"kumar"])

In [37]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [38]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [40]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

#### Python Numpy - Mathematical Function

In [41]:
arr1

array([[3, 9, 4, 9],
       [9, 9, 9, 9],
       [8, 9, 2, 4]])

In [42]:
np.sin(arr1)

array([[ 0.14112001,  0.41211849, -0.7568025 ,  0.41211849],
       [ 0.41211849,  0.41211849,  0.41211849,  0.41211849],
       [ 0.98935825,  0.41211849,  0.90929743, -0.7568025 ]])

In [43]:
np.cos(arr1)

array([[-0.9899925 , -0.91113026, -0.65364362, -0.91113026],
       [-0.91113026, -0.91113026, -0.91113026, -0.91113026],
       [-0.14550003, -0.91113026, -0.41614684, -0.65364362]])

In [44]:
np.tan(arr1)

array([[-0.14254654, -0.45231566,  1.15782128, -0.45231566],
       [-0.45231566, -0.45231566, -0.45231566, -0.45231566],
       [-6.79971146, -0.45231566, -2.18503986,  1.15782128]])

In [45]:
np.tanh(arr1)

array([[0.99505475, 0.99999997, 0.9993293 , 0.99999997],
       [0.99999997, 0.99999997, 0.99999997, 0.99999997],
       [0.99999977, 0.99999997, 0.96402758, 0.9993293 ]])

In [46]:
np.log10(arr1)

array([[0.47712125, 0.95424251, 0.60205999, 0.95424251],
       [0.95424251, 0.95424251, 0.95424251, 0.95424251],
       [0.90308999, 0.95424251, 0.30103   , 0.60205999]])

In [47]:
np.exp(arr1)

array([[2.00855369e+01, 8.10308393e+03, 5.45981500e+01, 8.10308393e+03],
       [8.10308393e+03, 8.10308393e+03, 8.10308393e+03, 8.10308393e+03],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 5.45981500e+01]])

In [48]:
np.sqrt(arr1)

array([[1.73205081, 3.        , 2.        , 3.        ],
       [3.        , 3.        , 3.        , 3.        ],
       [2.82842712, 3.        , 1.41421356, 2.        ]])

In [49]:
np.power(arr1,2)

array([[ 9, 81, 16, 81],
       [81, 81, 81, 81],
       [64, 81,  4, 16]], dtype=int32)

In [50]:
np.mean(arr1)

7.0

In [53]:
np.var(arr1)

7.333333333333333

In [54]:
np.min(arr1)

2

In [55]:
np.max(arr1)

9