#### Python Numpy - Sort, Search & Counting Functions

In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [3]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [4]:
np.searchsorted(arr, 34)

12

In [7]:
arr1 = np.array([0,345,454,0,0,0,0,0])
arr1

array([  0, 345, 454,   0,   0,   0,   0,   0])

In [8]:
np.count_nonzero(arr1)

2

In [9]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [10]:
np.where(arr >6)

(array([5, 8], dtype=int64),)

In [11]:
np.extract(arr > 6 ,arr)

array([ 72, 455])

#### Python Numpy - Byte Swapping

In [12]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [13]:
arr.byteswap()

array([  67108864,   50331648,   67108864,   83886080,  100663296,
       1207959552,   50331648,   50331648, -956235776,   83886080,
        100663296,  100663296])

#### Python Numpy - Copies and Views

In [14]:
a = np.copy(arr)

In [15]:
b = arr.view()

In [16]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [17]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [18]:
b[0]= 67

In [19]:
b

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [20]:
a

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

#### Python Numpy - Matrix Library

In [22]:
import numpy.matlib as nm

In [23]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [24]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#### Python Numpy - Linear Algebra

In [36]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [37]:
arr1

array([[0, 2],
       [3, 0]])

In [38]:
arr2

array([[1, 1],
       [1, 4]])

In [39]:
np.dot(arr1, arr2)

array([[2, 8],
       [3, 3]])

In [40]:
arr1@arr2

array([[2, 8],
       [3, 3]])